language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "ODm7bG2VhOGWEIxjk9UEA3y3DXbwMtkokC6NCX4ncmk/CJ23GaKObzgqYeVlqXrOuWQV/Qf8Vbw7NtG0WYX7TeMzc+A2Ans3NnbDwqjhwSFd597TQ0OU/HF/j3yQwWGpGLnwLIWxk7t18O8cHAWuSlpJiE1Ip5eF7m23kDXNkkI92G1+jhhg9ftRHNMYaVDShQ1LO8fTj06jdYknQZv3Js1L9gkUHHmWcTVztr5T5CQPGVaYpu2z+oyrvucR+JgbsRbeJEx97UaafpiUFBplsBc1nUHe3ych2NEa6or5nnbxfm+EEaLLxj5qK7jJTECOvYIu9piZlDwwCzj3kq2gljQpgO1ZISMB10JNdvafMUYMyZrGSixTvTzRgFPttGeJzsUeTrs2Dvz/nfyMgTKJh4xgTng5IBbWauQwEEs5TvWTPrOlFLx2Akbjh+b8GJLUL0e7pS8rNgBr7mLamdB3VCtZrhbGfkOX4aVggV2yt75Y2MPVBs5/JvByJ938yj3klCJsfKzyONtr8PKO7lxbJ/WdNJeebtHVumb7Tx8CFeNz4lBe0kMsg/PCBQyGcosz93JIeCGmUPbWhEPaBb0AznP5VD5w/crYlVulqP5yGurRkfIT12vUH8w+WBmm2rBZWKDBfLfp6Sv5yVdcO/UD0uF/NQb06485IaHXBvFLV10="
