language: node_js
node_js:
  - "node"
script:
  -
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "m1GwERphmcV112qOuF3EIdjcYXm9TltMSFQXxCRshmI0naEWUbssfEvZI9FW0QtP+yPFuTi1ULoFoh4bZ3cDPTppgDKDOd5ZUJSaZQX0WL5ME0tXPKb7eA4YZjuZoOeFg46HHWUyg/oVmoIClz9ymJ3OSZ4CGsLS6URoT+F0VCVHz07ekg4nN7fyiUjouyyzVEvCUIQcoJ2J53wlNtpcHU0Yk330u7O/tOPJvaXs/QRA9xxTknUVDJRZ1BI2FzLC33WKlvim2WY7GFH6Z3mnh/6kUNFoGayVOe/MHdG/e2lIvabcXGg3b5dNFDYsjd5Hh78w2CgE5pF7lN5sajfF1T0g/95F1cmHAKE4I/8/tkf/uKRDxz+JGTgLGyba4lj4OEDd2eQ5rATuZrLRtwZcpaHqgNYTXj7LEOeDdIZ4l3wQ+4hMHvQcUDk1ysOKU4iFPJ1lBvPkPEX9V5uPeN06uiVaSAUkmmtj1WroQBfc6mGzHsk8nzjQtU1Ee5R4idq/UZzRGIBpn58Q9d7TeXUDq9C6wlkFRLJNZrprsAqa1k8pD7Jt145o9ZKlCpjAKRXeEo65IcKPxJacjCDh7dEYyo3nPbtmMzFtB0mKsqgxSUHVxATTP3WaMePAe/bfhI1UrSbXyypnf3T5X8p5PWlwwJyVtdhRkDtw+iIiDJgyfm0="
